class AppStrings {
  static String get(String key, {bool isRussian = true}) {
    return isRussian ? _ru[key] ?? key : _en[key] ?? key;
  }

  static const Map<String, String> _ru = {
    'appName': 'Gryphone Invest',
    'appTagline': 'Симулируй • Прогнозируй • Тестируй',

    'navHome': 'Главная',
    'navPortfolio': 'Портфель',
    'navPredictions': 'ИИ',
    'navBacktest': 'Бэктест',
    'navSettings': 'Настройки',

    'totalPortfolioValue': 'Общая стоимость портфеля',
    'allTime': 'За всё время',
    'portfolioStats': 'Статистика портфеля',
    'totalGain': 'Общая прибыль',
    'returnLabel': 'Доходность',
    'cash': 'Наличные',
    'positions': 'Позиции',
    'marketWatch': 'Рынок',
    'performance': 'Динамика',
    'live': 'Онлайн',
    'week1': '1Н',
    'month1': '1М',
    'month3': '3М',

    'portfolio': 'Портфель',
    'addPosition': 'Добавить позицию',
    'noPositions': 'Нет позиций',
    'noPositionsSubtitle': 'Добавьте акцию в свой портфель',
    'allocation': 'Распределение',
    'invested': 'Вложено',
    'marketValue': 'Рыночная стоимость',
    'pnl': 'П/У',
    'avgCost': 'Ср. цена',
    'currentPrice': 'Тек. цена',
    'resetPortfolio': 'Сбросить портфель',
    'resetPortfolioSubtitle':
        'Вернуть 100 000\$ и удалить все позиции. Вы уверены?',
    'resetSuccess': 'Портфель успешно сброшен',

    'selectStock': 'Выберите акцию',
    'chooseStock': 'Выберите акцию...',
    'numberOfShares': 'Количество акций',
    'sharesHint': 'напр. 10',
    'sharesError': 'Введите количество акций',
    'sharesErrorZero': 'Должно быть больше 0',
    'pricePerShare': 'Цена за акцию',
    'shares': 'Акций',
    'totalCost': 'Итого',
    'availableCash': 'Доступно',
    'buyPosition': 'Купить позицию',

    'sellPosition': 'Продать позицию',
    'cancel': 'Отмена',
    'sell': 'Продать',

    'aiPredictions': 'ИИ Прогнозы',
    'all': 'Все',
    'bullish': 'Рост',
    'bearish': 'Падение',
    'neutral': 'Нейтрально',
    'current': 'Текущая',
    'aiConfidence': 'Уверенность ИИ',
    'days7': '7 дней',
    'days30': '30 дней',
    'days90': '90 дней',

    'backtesting': 'Бэктестинг',
    'configuration': 'Конфигурация',
    'strategy': 'Стратегия',
    'symbol': 'Тикер',
    'period': 'Период',
    'initialCapital': 'Начальный капитал',
    'runBacktest': 'Запустить бэктест',
    'runningBacktest': 'Идёт расчёт...',
    'results': 'Результаты',
    'profitable': '✓ Прибыльно',
    'loss': '✗ Убыток',
    'totalReturn': 'Доходность',
    'annualReturn': 'Годовая %',
    'maxDrawdown': 'Макс. просадка',
    'sharpeRatio': 'Коэф. Шарпа',
    'winRate': 'Винрейт',
    'totalTrades': 'Сделок',
    'finalCapital': 'Итоговый капитал',
    'equityCurve': 'Кривая доходности',
    'tradeSignals': 'Торговые сигналы',
    'days30label': '30 дней',
    'days60label': '60 дней',
    'days90label': '90 дней',

    'settings': 'Настройки',
    'appearance': 'Внешний вид',
    'darkMode': 'Тёмная тема',
    'darkModeOn': 'Включена',
    'darkModeOff': 'Выключена',
    'language': 'Язык',
    'languageDesc': 'Русский',
    'portfolioSection': 'Портфель',
    'resetPortfolioTitle': 'Сбросить портфель',
    'resetPortfolioDesc': 'Вернуть 100 000\$ наличных, убрать все позиции',
    'about': 'О приложении',
    'appVersion': 'Версия приложения',
    'disclaimer': 'Дисклеймер',
    'disclaimerText':
        'Только для образовательных целей. Не является финансовым советом.',
    'reset': 'Сбросить',
  };

  static const Map<String, String> _en = {
    'appName': 'Gryphone Invest',
    'appTagline': 'Simulate • Predict • Backtest',

    'navHome': 'Home',
    'navPortfolio': 'Portfolio',
    'navPredictions': 'AI',
    'navBacktest': 'Backtest',
    'navSettings': 'Settings',

    'totalPortfolioValue': 'Total Portfolio Value',
    'allTime': 'All time',
    'portfolioStats': 'Portfolio Stats',
    'totalGain': 'Total Gain',
    'returnLabel': 'Return',
    'cash': 'Cash',
    'positions': 'Positions',
    'marketWatch': 'Market Watch',
    'performance': 'Performance',
    'live': 'Live',
    'week1': '1W',
    'month1': '1M',
    'month3': '3M',

    'portfolio': 'Portfolio',
    'addPosition': 'Add Position',
    'noPositions': 'No positions yet',
    'noPositionsSubtitle': 'Start by adding a stock to your portfolio',
    'allocation': 'Allocation',
    'invested': 'Invested',
    'marketValue': 'Market Value',
    'pnl': 'P&L',
    'avgCost': 'Avg Cost',
    'currentPrice': 'Current Price',
    'resetPortfolio': 'Reset Portfolio',
    'resetPortfolioSubtitle':
        'This will remove all positions and restore your cash to \$100,000. Are you sure?',
    'resetSuccess': 'Portfolio reset successfully',

    'selectStock': 'Select Stock',
    'chooseStock': 'Choose a stock...',
    'numberOfShares': 'Number of Shares',
    'sharesHint': 'e.g. 10',
    'sharesError': 'Enter number of shares',
    'sharesErrorZero': 'Must be greater than 0',
    'pricePerShare': 'Price per share',
    'shares': 'Shares',
    'totalCost': 'Total Cost',
    'availableCash': 'Available Cash',
    'buyPosition': 'Buy Position',

    'sellPosition': 'Sell Position',
    'cancel': 'Cancel',
    'sell': 'Sell',

    'aiPredictions': 'AI Predictions',
    'all': 'All',
    'bullish': 'Bullish',
    'bearish': 'Bearish',
    'neutral': 'Neutral',
    'current': 'Current',
    'aiConfidence': 'AI Confidence',
    'days7': '7 days',
    'days30': '30 days',
    'days90': '90 days',

    'backtesting': 'Backtesting',
    'configuration': 'Configuration',
    'strategy': 'Strategy',
    'symbol': 'Symbol',
    'period': 'Period',
    'initialCapital': 'Initial Capital',
    'runBacktest': 'Run Backtest',
    'runningBacktest': 'Running...',
    'results': 'Results',
    'profitable': '✓ Profitable',
    'loss': '✗ Loss',
    'totalReturn': 'Total Return',
    'annualReturn': 'Annual Return',
    'maxDrawdown': 'Max Drawdown',
    'sharpeRatio': 'Sharpe Ratio',
    'winRate': 'Win Rate',
    'totalTrades': 'Total Trades',
    'finalCapital': 'Final Capital',
    'equityCurve': 'Equity Curve',
    'tradeSignals': 'Trade Signals',
    'days30label': '30 days',
    'days60label': '60 days',
    'days90label': '90 days',

    'settings': 'Settings',
    'appearance': 'Appearance',
    'darkMode': 'Dark Mode',
    'darkModeOn': 'Enabled',
    'darkModeOff': 'Disabled',
    'language': 'Language',
    'languageDesc': 'English',
    'portfolioSection': 'Portfolio',
    'resetPortfolioTitle': 'Reset Portfolio',
    'resetPortfolioDesc': 'Restore \$100,000 cash, remove all positions',
    'about': 'About',
    'appVersion': 'App Version',
    'disclaimer': 'Disclaimer',
    'disclaimerText':
        'For educational purposes only. Not financial advice.',
    'reset': 'Reset',
  };

  static Map<String, String> strategyNames(bool isRussian) => isRussian
      ? {
          'Moving Average Crossover': 'Пересечение скользящих',
          'RSI Momentum': 'RSI Моментум',
          'Bollinger Bands': 'Полосы Боллинджера',
          'Buy & Hold': 'Купить и держать',
          'Mean Reversion': 'Возврат к среднему',
        }
      : {
          'Moving Average Crossover': 'Moving Average Crossover',
          'RSI Momentum': 'RSI Momentum',
          'Bollinger Bands': 'Bollinger Bands',
          'Buy & Hold': 'Buy & Hold',
          'Mean Reversion': 'Mean Reversion',
        };
}
